[project]
name = "ring-to-3d"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dvc[s3]>=3.66.1",
    "hydra-core>=1.3.2",
    "matplotlib>=3.10.8",
]
